name: .NET Framework

on: [push]

jobs:
  build:
    runs-on: windows-2016
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build DotNET47
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\phduarte\tetris\src
