name: .NET 4.6

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build DotNET461
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\"
           dir
           MSBuild.exe $Env:GITHUB_WORKSPACE\phduarte\tetris\src
